# Generated by Django 4.2 on 2023-04-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contacts',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
