# Generated by Django 4.2 on 2023-04-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_alter_product_contacts_alter_product_delivery_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Seller',
        ),
    ]
