# Generated by Django 4.2 on 2023-05-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_product_details_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
